export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const TOGGLE_LOADER = "TOGGLE_LOADER";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const ADD_LOCATION = "ADD_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const GET_CONFIGS = "GET_CONFIGS";
export const GET_COMPANY = "GET_COMPANY";
export const EDIT_LOCATION = "EDIT_LOCATION";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const EDIT_CONFIG = "EDIT_CONFIG";
export const GET_FORM_DATA = "GET_FORM_DATA";
export const GET_FIELDS = "GET_FIELDS";
export const ADD_CUSTOM_FIELDS = "ADD_CUSTOM_FIELDS";
export const ADD_CUSTOM_OPTION_FIELDS = "ADD_CUSTOM_OPTION_FIELDS";
export const REGISTER_STAFF = "REGISTER_STAFF";
export const GET_STAFF = "GET_STAFF";
export const GET_SINGLE_STAFF = "GET_SINGLE_STAFF";
export const EDIT_STAFF = "EDIT_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";
export const DELETE_CUSTOM_FIELD = "DELETE_CUSTOM_FIELD";
export const REGISTER_VISITOR = "REGISTER_VISITOR";
export const GET_VISITORS = "GET_VISITORS";
export const GET_VISITOR = "GET_VISITOR";
export const SET_APPOINTMENT = "SET_APPOINTMENT";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const VISITOR_SIGN_OUT = "VISITOR_SIGN_OUT";
export const GET_STATS = "GET_STATS";
export const EDIT_CUSTOM_PURPOSE = "EDIT_CUSTOM_PURPOSE";
export const EDIT_CUSTOM_FIELD = "EDIT_CUSTOM_FIELD";
export const ADD_FIELD_OPTION = "ADD_FIELD_OPTION";
export const DELETE_CUSTOM_FIELD_OPTION = "DELETE_CUSTOM_FIELD_OPTION";
export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const GET_SINGLE_COMPANY = "GET_SINGLE_COMPANY";
export const EDIT_WORKSPACE_COMPANY = "EDIT_WORKSPACE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY"
export const UPLOAD_WELCOME_IMAGE = "UPLOAD_WELCOME_IMAGE";
export const DELETE_WELCOME_IMAGE = "DELETE_WELCOME_IMAGE";
export const GET_WELCOME_IMAGE = "GET_WELCOME_IMAGE";
export const GET_ATTENDANCE = "GET_ATTENDANCE";
export const GET_HOUSES = "GET_HOUSES";
export const ADD_HOUSE = "ADD_HOUSE";
export const GET_SINGLE_HOUSE = "GET_SINGLE_HOUSE";
export const EDIT_HOUSE = "EDIT_HOUSE";
export const DELETE_HOUSE = "DELETE_HOUSE"
export const DELETE_VISITOR = "DELETE_VISITOR"
export const GET_DIR = "GET_DIR";
export const ADD_DIR = "ADD_DIR";
export const EDIT_DIR = "EDIT_DIR";
export const GET_ONE_DIR = "GET_ONE_DIR";
export const DELETE_DIR = "DELETE_DIR"
export const GET_COMPANY_PURPOSE = "GET_COMPANY_PURPOSE"
export const GET_VISIT_PURPOSES = "GET_VISIT_PURPOSES"
export const GET_DEFAULT_VISIT_PURPOSES = "GET_DEFAULT_VISIT_PURPOSES"
export const SOUGHT_STAFF = "SOUGHT_STAFF"
export const GET_DEPARTMENT = "GET_DEPARTMENT"
export const SET_NEW_VISITOR = "SET_NEW_VISITOR"
export const GET_SLIDES = "GET_SLIDES"
export const GET_MOBILE_STAFF = "GET_MOBILE_STAFF"
export const GET_VISITOR_BY_NUMBER = "GET_VISITOR_BY_NUMBER"

export const GET_VISITORS_BY_LOCATION = "GET_VISITORS_BY_LOCATION"

export const GET_EVENTS = "GET_EVENTS"

export const GET_SINGLE_EVENT = "GET_SINGLE_EVENT"
export const GET_ALL_ATTENDEES = "GET_ALL_ATTENDEES"











